# ---- Site basics ----
title: "Dongchan (Don) Kim"
tagline: "Senior Staff Scientist • AI/ML Leader"
description: "Applied ML/LLM and multi-modal systems: large-scale search & recommendations, real-time decisioning, representation learning, distillation, ensembles, transfer learning."
url: "https://dongchankim-io.github.io"   # Canonical URL for this GitHub Pages site
baseurl: ""                               # Keep empty for user/organization sites

# Custom links (handy in templates)
personal_website: "https://dongchankim.io"
external_blog: "https://blog.dongchankim.io"

# Time/locale
timezone: "America/Los_Angeles"
lang: en

# ---- Theme ----
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/dongchankim-io" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN" }

# Show specific pages in the top nav (create these files in repo root)
header_pages:
  - index.md
  - about.md
  - projects.md
  - publications.md
  - blog.md   # tip: make this a redirect to your external blog

# ---- Build & content settings ----
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: false
  math_engine: mathjax

# ---- Collections ----
collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

# ---- Defaults ----
defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
      author: "Dongchan Kim"
      toc: true
  - scope: { path: "", type: "pages" }
    values:
      layout: page
      author: "Dongchan Kim"
  - scope: { path: "", type: "projects" }
    values:
      layout: page
  - scope: { path: "", type: "publications" }
    values:
      layout: page

# ---- Author / SEO metadata ----
author:
  name: "Dongchan (Don) Kim"
  email: "dongchan@dongchankim.io"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# jekyll-seo-tag extra fields (helps discovery)
social:
  name: "Dongchan (Don) Kim"
  links:
    - "https://github.com/dongchankim-io"
    - "https://www.linkedin.com/in/dongchan"
    - "https://dongchankim.io"          # personal website
    - "https://blog.dongchankim.io"     # external blog

# Analytics (optional)
# google_analytics: "G-XXXXXXXXXX"

# ---- Build hygiene ----
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  - vendor
  - scripts
include:
  - CNAME   # only if you later use a custom domain

future: false
strict_front_matter: false
