# ---- Site basics ----
title: "DonK Projects"
tagline: "Open Source Projects & Code Showcase"
description: "A showcase of my public GitHub repositories and open source contributions in AI/ML, search & recommendations, and real-time systems."
url: "https://dongchankim-io.github.io"   # Canonical URL for this GitHub Pages site
baseurl: ""                               # Keep empty for user/organization sites

# Custom links (handy in templates)
personal_website: "https://dongchankim.io"
external_blog: "https://blog.dongchankim.io"

# Time/locale
timezone: "America/Los_Angeles"
lang: en

# ---- Theme ----
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/dongchankim-io" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN" }
  # Favicon configuration
  favicon: /favicon.ico
  favicon_png: /favicon.png

# Show specific pages in the top nav (create these files in repo root)
header_pages:
  - index.md

# ---- Build & content settings ----
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: false
  math_engine: mathjax

# ---- Collections ----
collections:
  projects:
    output: true
    permalink: /projects/:path/

# ---- Defaults ----
defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
      author: "Dongchan Kim"
      toc: true
  - scope: { path: "", type: "pages" }
    values:
      layout: page
      author: "Dongchan Kim"
  - scope: { path: "", type: "projects" }
    values:
      layout: page


# ---- Author / SEO metadata ----
author:
  name: "Dongchan (Don) Kim"
  email: "dongchan@dongchankim.io"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# jekyll-seo-tag extra fields (helps discovery)
social:
  name: "Dongchan (Don) Kim"
  links:
    - "https://github.com/dongchankim-io"
    - "https://www.linkedin.com/in/dongchan"
    - "https://dongchankim.io"          # personal website
    - "https://blog.dongchankim.io"     # external blog

# Analytics (optional)
# google_analytics: "G-XXXXXXXXXX"

# ---- Build hygiene ----
exclude:
  - README.md
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  - vendor
  - scripts
include:
  - CNAME   # only if you later use a custom domain

future: false
strict_front_matter: false
